name: rdtc
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.8.8
- pytorch=1.8.1
- torchvision=0.9.1
- cudatoolkit=10.2
- numpy=1.20.2
- pandas=1.2.3
- imageio=2.9.0
- tensorboard=2.4.1
- tqdm=4.59.0
